### ISSUE TITLE
azimuthEventsInRange query doesn't work

### ISSUE THREAD

**Issue by zramsay** [cerc-io/azimuth-watcher-ts#28]
for example, this query:
```
query MyQuery {
  azimuthEventsInRange(toBlockNumber: 18569500, fromBlockNumber: 18569000) {
    event {
      ... on ChangedKeysEvent {
        __typename
        point
        keyRevisionNumber
        encryptionKey
        authenticationKey
        cryptoSuiteVersion
      }
    }
  }
} 
```
gives this error message:
```
{
  "errors": [
    {
      "message": "Range not available, expected 501, got 0 blocks in range",
      "path": [
        "azimuthEventsInRange"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Range not available, expected 501, got 0 blocks in range",
            "    at <anonymous> (/app/packages/azimuth-watcher/src/resolvers.ts:888:17)",
            "    at step (/app/packages/azimuth-watcher/src/resolvers.ts:3:3)",
            "    at Object.next (/app/packages/azimuth-watcher/src/resolvers.ts:3:3)",
            "    at fulfilled (/app/packages/azimuth-watcher/src/resolvers.ts:3:3)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "azimuthEventsInRange": null
  }
}
```

**Comment by nikugogoi** [comment]
The events query will not work as the deployed watchers are lazy watchers.
The live azimuth contracts are mentioned in https://github.com/urbit/azimuth#live-contracts
Which contract's events are we interested in?

**Comment by AFDudley** [comment]
Why not just do all of them? We should have sufficient archive nodes to support this, we also have the chain chunker machines, it's unclear to me why those wouldn't be used as well.

**Comment by nikugogoi** [comment]
The watchers have been redeployed in active mode at https://azimuth.dev.vdb.to/graphql
The `eventsInRange` GQL query is working now
```graphql
query MyQuery {
  azimuthEventsInRange(toBlockNumber: 18569500, fromBlockNumber: 18569000) {
    event {
      ... on ChangedKeysEvent {
        point
        keyRevisionNumber
        encryptionKey
        authenticationKey
        cryptoSuiteVersion
      }
      __typename
    }
  }
}
```
Response:
```json
{
  "data": {
    "azimuthEventsInRange": [
      {
        "event": {
          "__typename": "BrokeContinuityEvent"
        }
      },
      {
        "event": {
          "point": "199494579",
          "keyRevisionNumber": "2",
          "encryptionKey": "0x71f9bf6ab2809dbce57ab08ab653c59c24d23cdabfb2d530d0a858eea44f27a9",
          "authenticationKey": "0xbea6ccd1eea575cb227b57c38bbf58aec31440545e93787b0f3896f71ff9b47f",
          "cryptoSuiteVersion": "1",
          "__typename": "ChangedKeysEvent"
        }
      }
    ]
  }
}
```

Example `eventsInRange` GQL queries for other watchers:
```graphql
query {
  pollsEventsInRange(toBlockNumber: 7038500, fromBlockNumber: 7038000) {
    event { __typename }
    block { number }
  }
  linearStarReleaseEventsInRange(toBlockNumber: 13154000, fromBlockNumber: 13153500) {
    event { __typename }
    block { number }
  }
  eclipticEventsInRange(toBlockNumber: 18646500, fromBlockNumber: 18646000) {
    event { __typename }
    block { number }
  }
  delegatedSendingEventsInRange(toBlockNumber: 6785000, fromBlockNumber: 6784956) {
    event { __typename }
    block { number }
  }
  conditionalStarReleaseEventsInRange(toBlockNumber: 11637500, fromBlockNumber: 11637000) {
    event { __typename }
    block { number }
  }
  claimsEventsInRange(toBlockNumber: 7824000, fromBlockNumber: 7823500) {
    event { __typename }
    block { number }
  }
  censuresEventsInRange(toBlockNumber: 11175500, fromBlockNumber: 11175000) {
    event { __typename }
    block { number }
  }
}
```

**Comment by zramsay** [comment]
works in v2
